# BASED ON  http://kiko.gfjaru.com/  #

# Basic
name:               "discrete subgroup"
description:        "London-ish Lattice Coding & Crypto Meetings"

url:                "http://malb.io/"
author:             "malb"

# URL
baseurl:            "/discrete-subgroup"
permalink:          pretty

# Markdown
markdown:           kramdown

# Navigation
nav:
  - name:           "About"
    href:           "about"

  - name:           "Lyon"
    href:           "http://perso.ens-lyon.fr/damien.stehle/LATTICE_MEETINGS.html"

  - name:           "<i class='fa fa-github'></i>"
    href:           "https://github.com/malb/discrete-subgroup"

  - name:           "<i class='fa fa-rss'></i>"
    href:           "feed.xml"

  - name:           "<i class='fa fa-twitter'></i>"
    href:           "https://twitter.com/search?q=%23l2c2m1"

# Sass
sass:
  style:            :compressed

# Analytics
google_analytics: true
tracking_id: "UA-74639670-1"

gems:
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"


timezone:    Europe/London
future:      true
