# BASED ON  http://kiko.gfjaru.com/  #

# Basic
name:               "discrete subgroup"
description:        "London-ish Lattice Coding & Crypto Meetings"

url:                "http://malb.io/"
author:             "malb"

# URL
baseurl:            "/discrete-subgroup"
permalink:          pretty

# Markdown
markdown:           kramdown

# Navigation
nav:
  - name:           "About"
    href:           "about"

  - name:           "Lyon Lattice Meetings"
    href:           "http://perso.ens-lyon.fr/damien.stehle/LATTICE_MEETINGS.html"

  - name:           "Source"
    href:           "https://github.com/malb/discrete-subgroup"

# Sass
sass:
  style:            :compressed

# Analytics
analytics :
  provider : google
  google :
    tracking_id : "UA-74639670-1"

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"


timezone:    Europe/London
future:      true
